# Generated by Django 5.2.14 on 2026-05-18 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "channel_id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="채널 ID",
                    ),
                ),
                (
                    "channel_url",
                    models.CharField(max_length=300, verbose_name="수집 URL"),
                ),
                (
                    "channel_name",
                    models.CharField(max_length=200, verbose_name="채널명"),
                ),
                (
                    "subscriber_count",
                    models.BigIntegerField(default=0, verbose_name="구독자 수"),
                ),
                (
                    "video_count",
                    models.IntegerField(default=0, verbose_name="수집 영상 수"),
                ),
                (
                    "total_view_count",
                    models.BigIntegerField(default=0, verbose_name="채널 전체 조회수"),
                ),
                ("description", models.TextField(blank=True, verbose_name="채널 설명")),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="채널 썸네일"
                    ),
                ),
                (
                    "banner_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="채널 배너 이미지"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="국가 코드"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 수집일시"),
                ),
            ],
            options={
                "verbose_name": "채널",
                "verbose_name_plural": "채널 목록",
                "db_table": "channel",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="태그명"
                    ),
                ),
            ],
            options={
                "verbose_name": "태그",
                "verbose_name_plural": "태그 목록",
                "db_table": "tag",
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "video_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="영상 ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="영상 제목")),
                ("description", models.TextField(blank=True, verbose_name="영상 설명")),
                (
                    "published_at",
                    models.DateField(blank=True, null=True, verbose_name="게시일"),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(default=0, verbose_name="영상 길이(초)"),
                ),
                (
                    "is_short",
                    models.BooleanField(default=False, verbose_name="Shorts 여부"),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=500, verbose_name="썸네일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 수집일시"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="api_v1.channel",
                        verbose_name="채널",
                    ),
                ),
            ],
            options={
                "verbose_name": "영상",
                "verbose_name_plural": "영상 목록",
                "db_table": "video",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("running", "수집중"),
                            ("done", "완료"),
                            ("error", "오류"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "total_videos",
                    models.IntegerField(default=0, verbose_name="전체 영상 수"),
                ),
                (
                    "collected_videos",
                    models.IntegerField(default=0, verbose_name="수집 완료 수"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="오류 메시지"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="시작일시"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료일시"
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_logs",
                        to="api_v1.channel",
                        verbose_name="채널",
                    ),
                ),
            ],
            options={
                "verbose_name": "수집 로그",
                "verbose_name_plural": "수집 로그 목록",
                "db_table": "collection_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoStats",
            fields=[
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="stats",
                        serialize=False,
                        to="api_v1.video",
                        verbose_name="영상",
                    ),
                ),
                (
                    "view_count",
                    models.BigIntegerField(default=0, verbose_name="조회수"),
                ),
                (
                    "like_count",
                    models.IntegerField(default=0, verbose_name="좋아요 수"),
                ),
                (
                    "comment_count",
                    models.IntegerField(default=0, verbose_name="댓글 수"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="업데이트일시"),
                ),
            ],
            options={
                "verbose_name": "영상 통계",
                "verbose_name_plural": "영상 통계 목록",
                "db_table": "video_stats",
            },
        ),
        migrations.CreateModel(
            name="VideoStatsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "view_count",
                    models.BigIntegerField(default=0, verbose_name="조회수"),
                ),
                (
                    "like_count",
                    models.IntegerField(default=0, verbose_name="좋아요 수"),
                ),
                (
                    "comment_count",
                    models.IntegerField(default=0, verbose_name="댓글 수"),
                ),
                (
                    "snapshot_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="스냅샷 일시"),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="api_v1.video",
                        verbose_name="영상",
                    ),
                ),
            ],
            options={
                "verbose_name": "영상 통계 스냅샷",
                "verbose_name_plural": "영상 통계 스냅샷 목록",
                "db_table": "video_stats_snapshot",
                "ordering": ["snapshot_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_tags",
                        to="api_v1.tag",
                        verbose_name="태그",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_tags",
                        to="api_v1.video",
                        verbose_name="영상",
                    ),
                ),
            ],
            options={
                "verbose_name": "영상 태그",
                "verbose_name_plural": "영상 태그 목록",
                "db_table": "video_tag",
            },
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["channel", "published_at"], name="video_channel_059845_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videostatssnapshot",
            index=models.Index(
                fields=["video", "snapshot_at"], name="video_stats_video_i_19ac9a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="videotag",
            unique_together={("video", "tag")},
        ),
    ]
