# Generated by Django 5.2.14 on 2026-05-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webcrawl", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="ko_title",
            field=models.CharField(default="", max_length=255, null=True),
        ),
    ]
